mp_pictures:
    resource: "@MPPicturesBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: MPUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout